version: "3"
services:
  front:
    build:
      context: front
    ports:
      - 3000:3000
    volumes: 
      - ./front/src:/app/front/src
      - ./front/public:/app/front/public
      - ./common:/app/common
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - default
  mysql:
    build:
      context: mysql
    volumes:
      - ./mysql/initsql:/docker-entrypoint-initdb.d/
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql
    networks:
      - default
  goserv:
    build:
      context: goserv
    environment:
      - TZ='Asia/Tokyo'
    depends_on:
      - mysql
    networks:
      - default
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logrotate.conf:/etc/logrotate.d/nginx
    depends_on:
      - front
      - goserv
    networks:
      - default
  back:
    build:
      context: back
    ports:
      - 3001:3001
    volumes:
      - ./back:/app/back
      - ./common:/app/common

networks:
  shared-network:
    external: true

      